name: "test"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  lint: 
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/setup-go@v2"
      with:
        go-version: "^1.17"
    - name: "Install linting tools"
      run: |
        # This is done before checking out, as to not modify go.mod
        go install mvdan.cc/gofumpt/gofumports@latest
        go install github.com/mgechev/revive@latest
    - uses: "actions/checkout@v2"
    - name: "Go Mod Tidy"
      run: "go mod tidy && bash -c '[ $(git status --porcelain | tee /dev/fd/2 | wc -c) -eq 0 ]'"
    - name: "Formatting (gofumpt)"
      run: |
        GOFUMPT_OUTPUT="$(find . -iname '*.go' -type f | xargs gofumports -d)"
        if [ -n "$GOFUMPT_OUTPUT" ]; then
          echo "All the following files are not correctly formatted"
          echo "${GOFUMPT_OUTPUT}"
          exit 1
        fi
    - name: "Linting (revive)"
      run: "bash -c '[ $(revive ./... | tee /dev/fd/2 | wc -c) -eq 0 ]'"
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: "^1.17"
    - name: "go test"
      run: "go test ./..."
